layout_spectrum: 0.6009743
typography_spectrum: 0.1973018
color:
  saturation: 0.08094435
  brandStrength: 0.9921808
  lightness: 0.7984823
  rhythmicContrast: 0.9047217
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
name: Phenommnomm
